### ISSUE TITLE
gem не компилируется на платформы i386 и ARM

### ISSUE THREAD

**Issue by Muscul** [Unact/kkm#15]
Не планируете добавить поддержку архитектур i386 и ARM? 
Для правильной сборки native extension нужно подключать правильную версию библиотеки libfptr.so

**Comment by DCrow** [comment]
В ближайшее время не планируем, но мы не против сторонних доработок

**Comment by DCrow** [comment]
После перехода на ДТО 10, gem доработан с возможностью подключения других архитектур
