### ISSUE TITLE
Ошибка: 9 [Не удалось получить значение настройки [Port]]

### ISSUE THREAD

**Issue by Muscul** [Unact/kkm#20]
При использовании версии  драйвера 10.7.0.0, не удаётся установить подключение к принтеру Атол 30Ф.  

Похоже проблема с новым драйвером, на предыдущей версии этой проблемы нет.

ruby[5002:757565] T:016EC000 INFO  [FiscalPrinter] libfptr_set_settings() 
ruby[5002:757565] T:016EC000 INFO  [FiscalPrinter] Новые настройки: [{"DeviceName":"ATOLFptr","Port":"TTY","TTYSuffix":"/dev/ttyACM0","BaudRate":115200,"Model":61,"Protocol":0,"Parity":0,"ttyACM0":61,"StopBits":0}]
ruby[5002:757565] T:016EC000 ERROR [FiscalPrinter] Объекту 0x87AC01C0 присвоен код ошибки 9 [Не удалось получить значение настройки [Port]]

**Comment by DCrow** [comment]
Добрый день!

Судя по приложенной логе в настройку `Port`, передается неверное значение. 
Необходимо передавать значение из переменной `KKM::LibFptr::LIBFPTR_PORT_COM`

Другие настройки тоже возможно не верные, так как в 10 драйвере было изменение в найстройках, и какие значения передавать.

**Comment by Muscul** [comment]
Спасибо, разобрался.

Да, в новой версии Port имеет численное значение. Т.е. для USB интерфейса Port = 1.
Остальные параметры тоже проверю.
